/*
This script has been generated by Nickk's TextDraw editor
Au"IA YRA PRISIJUNGIMAS
*/

//VARIABLES
new PlayerText:textdraw_0[MAX_PLAYERS];
new PlayerText:textdraw_1[MAX_PLAYERS];
new PlayerText:textdraw_2[MAX_PLAYERS];
new Text:textdraw_3;
new PlayerText:textdraw_4[MAX_PLAYERS];
new PlayerText:textdraw_5[MAX_PLAYERS];
new PlayerText:textdraw_6[MAX_PLAYERS];
new PlayerText:textdraw_7[MAX_PLAYERS];
new PlayerText:textdraw_8[MAX_PLAYERS];
new PlayerText:textdraw_9[MAX_PLAYERS];
new PlayerText:textdraw_10[MAX_PLAYERS];
new PlayerText:textdraw_11[MAX_PLAYERS];
new PlayerText:textdraw_12[MAX_PLAYERS];
new PlayerText:textdraw_13[MAX_PLAYERS];
new PlayerText:textdraw_14[MAX_PLAYERS];
new PlayerText:textdraw_15[MAX_PLAYERS];
new PlayerText:textdraw_16[MAX_PLAYERS];
new PlayerText:textdraw_17[MAX_PLAYERS];
new PlayerText:textdraw_18[MAX_PLAYERS];
new PlayerText:textdraw_19[MAX_PLAYERS];
new PlayerText:textdraw_20[MAX_PLAYERS];
new PlayerText:textdraw_21[MAX_PLAYERS];
new PlayerText:textdraw_22[MAX_PLAYERS];
new PlayerText:textdraw_23[MAX_PLAYERS];
new PlayerText:textdraw_24[MAX_PLAYERS];
new PlayerText:textdraw_25[MAX_PLAYERS];

//TEXTDRAWS
textdraw_0[playerid] = CreatePlayerTextDraw(playerid, 295.000000, 119.000000, "_");
PlayerTextDrawFont(playerid, textdraw_0[playerid], 1);
PlayerTextDrawLetterSize(playerid, textdraw_0[playerid], 0.508333, 25.599992);
PlayerTextDrawTextSize(playerid, textdraw_0[playerid], 314.000000, 342.500000);
PlayerTextDrawSetOutline(playerid, textdraw_0[playerid], 1);
PlayerTextDrawSetShadow(playerid, textdraw_0[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_0[playerid], 2);
PlayerTextDrawColor(playerid, textdraw_0[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_0[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_0[playerid], 1296911751);
PlayerTextDrawUseBox(playerid, textdraw_0[playerid], 1);
PlayerTextDrawSetProportional(playerid, textdraw_0[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_0[playerid], 0);

textdraw_1[playerid] = CreatePlayerTextDraw(playerid, 123.000000, 119.000000, "_");
PlayerTextDrawFont(playerid, textdraw_1[playerid], 1);
PlayerTextDrawLetterSize(playerid, textdraw_1[playerid], 0.600000, 25.600032);
PlayerTextDrawTextSize(playerid, textdraw_1[playerid], 298.500000, -1.000000);
PlayerTextDrawSetOutline(playerid, textdraw_1[playerid], 1);
PlayerTextDrawSetShadow(playerid, textdraw_1[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_1[playerid], 2);
PlayerTextDrawColor(playerid, textdraw_1[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_1[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_1[playerid], 2094792839);
PlayerTextDrawUseBox(playerid, textdraw_1[playerid], 1);
PlayerTextDrawSetProportional(playerid, textdraw_1[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_1[playerid], 0);

textdraw_2[playerid] = CreatePlayerTextDraw(playerid, 467.000000, 119.000000, "_");
PlayerTextDrawFont(playerid, textdraw_2[playerid], 1);
PlayerTextDrawLetterSize(playerid, textdraw_2[playerid], 0.600000, 25.600032);
PlayerTextDrawTextSize(playerid, textdraw_2[playerid], 298.500000, -1.000000);
PlayerTextDrawSetOutline(playerid, textdraw_2[playerid], 1);
PlayerTextDrawSetShadow(playerid, textdraw_2[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_2[playerid], 2);
PlayerTextDrawColor(playerid, textdraw_2[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_2[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_2[playerid], 2094792839);
PlayerTextDrawUseBox(playerid, textdraw_2[playerid], 1);
PlayerTextDrawSetProportional(playerid, textdraw_2[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_2[playerid], 0);

textdraw_3 = TextDrawCreate(295.000000, 351.000000, "_");
TextDrawFont(textdraw_3, 1);
TextDrawLetterSize(textdraw_3, 0.600000, -0.099996);
TextDrawTextSize(textdraw_3, 298.500000, 342.500000);
TextDrawSetOutline(textdraw_3, 1);
TextDrawSetShadow(textdraw_3, 0);
TextDrawAlignment(textdraw_3, 2);
TextDrawColor(textdraw_3, -1);
TextDrawBackgroundColor(textdraw_3, 255);
TextDrawBoxColor(textdraw_3, 2094792839);
TextDrawUseBox(textdraw_3, 1);
TextDrawSetProportional(textdraw_3, 1);
TextDrawSetSelectable(textdraw_3, 0);

textdraw_4[playerid] = CreatePlayerTextDraw(playerid, 295.000000, 118.000000, "_");
PlayerTextDrawFont(playerid, textdraw_4[playerid], 1);
PlayerTextDrawLetterSize(playerid, textdraw_4[playerid], 0.600000, -0.099996);
PlayerTextDrawTextSize(playerid, textdraw_4[playerid], 298.500000, 342.500000);
PlayerTextDrawSetOutline(playerid, textdraw_4[playerid], 1);
PlayerTextDrawSetShadow(playerid, textdraw_4[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_4[playerid], 2);
PlayerTextDrawColor(playerid, textdraw_4[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_4[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_4[playerid], 2094792839);
PlayerTextDrawUseBox(playerid, textdraw_4[playerid], 1);
PlayerTextDrawSetProportional(playerid, textdraw_4[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_4[playerid], 0);

textdraw_5[playerid] = CreatePlayerTextDraw(playerid, 224.000000, 119.000000, "_");
PlayerTextDrawFont(playerid, textdraw_5[playerid], 1);
PlayerTextDrawLetterSize(playerid, textdraw_5[playerid], 0.600000, 25.600032);
PlayerTextDrawTextSize(playerid, textdraw_5[playerid], 298.500000, -2.000000);
PlayerTextDrawSetOutline(playerid, textdraw_5[playerid], 1);
PlayerTextDrawSetShadow(playerid, textdraw_5[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_5[playerid], 2);
PlayerTextDrawColor(playerid, textdraw_5[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_5[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_5[playerid], 2094792839);
PlayerTextDrawUseBox(playerid, textdraw_5[playerid], 1);
PlayerTextDrawSetProportional(playerid, textdraw_5[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_5[playerid], 0);

textdraw_6[playerid] = CreatePlayerTextDraw(playerid, 136.000000, 270.000000, "Musu serverio svetaine");
PlayerTextDrawFont(playerid, textdraw_6[playerid], 2);
PlayerTextDrawLetterSize(playerid, textdraw_6[playerid], 0.137500, 0.750000);
PlayerTextDrawTextSize(playerid, textdraw_6[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, textdraw_6[playerid], 0);
PlayerTextDrawSetShadow(playerid, textdraw_6[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_6[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_6[playerid], 9109759);
PlayerTextDrawBackgroundColor(playerid, textdraw_6[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_6[playerid], 50);
PlayerTextDrawUseBox(playerid, textdraw_6[playerid], 0);
PlayerTextDrawSetProportional(playerid, textdraw_6[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_6[playerid], 0);

textdraw_7[playerid] = CreatePlayerTextDraw(playerid, 153.000000, 282.000000, "www.nrmg.lt");
PlayerTextDrawFont(playerid, textdraw_7[playerid], 2);
PlayerTextDrawLetterSize(playerid, textdraw_7[playerid], 0.137500, 0.750000);
PlayerTextDrawTextSize(playerid, textdraw_7[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, textdraw_7[playerid], 0);
PlayerTextDrawSetShadow(playerid, textdraw_7[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_7[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_7[playerid], 9109759);
PlayerTextDrawBackgroundColor(playerid, textdraw_7[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_7[playerid], 50);
PlayerTextDrawUseBox(playerid, textdraw_7[playerid], 0);
PlayerTextDrawSetProportional(playerid, textdraw_7[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_7[playerid], 0);

textdraw_8[playerid] = CreatePlayerTextDraw(playerid, 133.000000, 309.000000, "Musu teamspeak serveris");
PlayerTextDrawFont(playerid, textdraw_8[playerid], 2);
PlayerTextDrawLetterSize(playerid, textdraw_8[playerid], 0.137500, 0.750000);
PlayerTextDrawTextSize(playerid, textdraw_8[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, textdraw_8[playerid], 0);
PlayerTextDrawSetShadow(playerid, textdraw_8[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_8[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_8[playerid], 9109759);
PlayerTextDrawBackgroundColor(playerid, textdraw_8[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_8[playerid], 50);
PlayerTextDrawUseBox(playerid, textdraw_8[playerid], 0);
PlayerTextDrawSetProportional(playerid, textdraw_8[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_8[playerid], 0);

textdraw_9[playerid] = CreatePlayerTextDraw(playerid, 156.000000, 322.000000, "ts.nrmg.lt");
PlayerTextDrawFont(playerid, textdraw_9[playerid], 2);
PlayerTextDrawLetterSize(playerid, textdraw_9[playerid], 0.137500, 0.750000);
PlayerTextDrawTextSize(playerid, textdraw_9[playerid], 394.500000, 14.000000);
PlayerTextDrawSetOutline(playerid, textdraw_9[playerid], 0);
PlayerTextDrawSetShadow(playerid, textdraw_9[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_9[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_9[playerid], 9109759);
PlayerTextDrawBackgroundColor(playerid, textdraw_9[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_9[playerid], 50);
PlayerTextDrawUseBox(playerid, textdraw_9[playerid], 0);
PlayerTextDrawSetProportional(playerid, textdraw_9[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_9[playerid], 0);

textdraw_10[playerid] = CreatePlayerTextDraw(playerid, 128.000000, 141.000000, "Nowy_TextDraw");
PlayerTextDrawFont(playerid, textdraw_10[playerid], 5);
PlayerTextDrawLetterSize(playerid, textdraw_10[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, textdraw_10[playerid], 91.500000, 127.000000);
PlayerTextDrawSetOutline(playerid, textdraw_10[playerid], 1);
PlayerTextDrawSetShadow(playerid, textdraw_10[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_10[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_10[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_10[playerid], 0);
PlayerTextDrawBoxColor(playerid, textdraw_10[playerid], 255);
PlayerTextDrawUseBox(playerid, textdraw_10[playerid], 1);
PlayerTextDrawSetProportional(playerid, textdraw_10[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_10[playerid], 0);
PlayerTextDrawSetPreviewModel(playerid, textdraw_10[playerid], 296);
PlayerTextDrawSetPreviewRot(playerid, textdraw_10[playerid], -10.000000, 0.000000, -30.000000, 1.000000);
PlayerTextDrawSetPreviewVehCol(playerid, textdraw_10[playerid], 8, 1);

textdraw_11[playerid] = CreatePlayerTextDraw(playerid, 131.000000, 121.000000, "NRMG");
PlayerTextDrawFont(playerid, textdraw_11[playerid], 2);
PlayerTextDrawLetterSize(playerid, textdraw_11[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, textdraw_11[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, textdraw_11[playerid], 1);
PlayerTextDrawSetShadow(playerid, textdraw_11[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_11[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_11[playerid], -2686721);
PlayerTextDrawBackgroundColor(playerid, textdraw_11[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_11[playerid], 50);
PlayerTextDrawUseBox(playerid, textdraw_11[playerid], 0);
PlayerTextDrawSetProportional(playerid, textdraw_11[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_11[playerid], 0);

textdraw_12[playerid] = CreatePlayerTextDraw(playerid, 201.000000, 129.000000, ". LT");
PlayerTextDrawFont(playerid, textdraw_12[playerid], 2);
PlayerTextDrawLetterSize(playerid, textdraw_12[playerid], 0.212500, 0.850000);
PlayerTextDrawTextSize(playerid, textdraw_12[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, textdraw_12[playerid], 1);
PlayerTextDrawSetShadow(playerid, textdraw_12[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_12[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_12[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_12[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_12[playerid], 50);
PlayerTextDrawUseBox(playerid, textdraw_12[playerid], 0);
PlayerTextDrawSetProportional(playerid, textdraw_12[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_12[playerid], 0);

textdraw_13[playerid] = CreatePlayerTextDraw(playerid, 284.000000, 332.000000, "PRISIJUNGIMAS");
PlayerTextDrawFont(playerid, textdraw_13[playerid], 2);
PlayerTextDrawLetterSize(playerid, textdraw_13[playerid], 0.258332, 1.750000);
PlayerTextDrawTextSize(playerid, textdraw_13[playerid], 20.000000, 117.000000);
PlayerTextDrawSetOutline(playerid, textdraw_13[playerid], 1);
PlayerTextDrawSetShadow(playerid, textdraw_13[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_13[playerid], 2);
PlayerTextDrawColor(playerid, textdraw_13[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_13[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_13[playerid], 16711830);
PlayerTextDrawUseBox(playerid, textdraw_13[playerid], 1);
PlayerTextDrawSetProportional(playerid, textdraw_13[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_13[playerid], 1);

textdraw_14[playerid] = CreatePlayerTextDraw(playerid, 405.000000, 332.000000, "REGISTRACIJA");
PlayerTextDrawFont(playerid, textdraw_14[playerid], 2);
PlayerTextDrawLetterSize(playerid, textdraw_14[playerid], 0.258332, 1.750000);
PlayerTextDrawTextSize(playerid, textdraw_14[playerid], 22.500000, 119.500000);
PlayerTextDrawSetOutline(playerid, textdraw_14[playerid], 1);
PlayerTextDrawSetShadow(playerid, textdraw_14[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_14[playerid], 2);
PlayerTextDrawColor(playerid, textdraw_14[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_14[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_14[playerid], -2686826);
PlayerTextDrawUseBox(playerid, textdraw_14[playerid], 1);
PlayerTextDrawSetProportional(playerid, textdraw_14[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_14[playerid], 1);

textdraw_15[playerid] = CreatePlayerTextDraw(playerid, 345.000000, 331.000000, "_");
PlayerTextDrawFont(playerid, textdraw_15[playerid], 1);
PlayerTextDrawLetterSize(playerid, textdraw_15[playerid], 0.600000, -0.249997);
PlayerTextDrawTextSize(playerid, textdraw_15[playerid], 298.500000, 239.500000);
PlayerTextDrawSetOutline(playerid, textdraw_15[playerid], 1);
PlayerTextDrawSetShadow(playerid, textdraw_15[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_15[playerid], 2);
PlayerTextDrawColor(playerid, textdraw_15[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_15[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_15[playerid], 2094792839);
PlayerTextDrawUseBox(playerid, textdraw_15[playerid], 1);
PlayerTextDrawSetProportional(playerid, textdraw_15[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_15[playerid], 0);

textdraw_16[playerid] = CreatePlayerTextDraw(playerid, 298.000000, 118.000000, "Prisijungimas");
PlayerTextDrawFont(playerid, textdraw_16[playerid], 1);
PlayerTextDrawLetterSize(playerid, textdraw_16[playerid], 0.349999, 1.549998);
PlayerTextDrawTextSize(playerid, textdraw_16[playerid], 390.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, textdraw_16[playerid], 1);
PlayerTextDrawSetShadow(playerid, textdraw_16[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_16[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_16[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_16[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_16[playerid], 50);
PlayerTextDrawUseBox(playerid, textdraw_16[playerid], 0);
PlayerTextDrawSetProportional(playerid, textdraw_16[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_16[playerid], 0);

textdraw_17[playerid] = CreatePlayerTextDraw(playerid, 246.000000, 152.000000, "Sveiki sugryze i");
PlayerTextDrawFont(playerid, textdraw_17[playerid], 1);
PlayerTextDrawLetterSize(playerid, textdraw_17[playerid], 0.312500, 1.100000);
PlayerTextDrawTextSize(playerid, textdraw_17[playerid], 439.500000, 17.000000);
PlayerTextDrawSetOutline(playerid, textdraw_17[playerid], 0);
PlayerTextDrawSetShadow(playerid, textdraw_17[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_17[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_17[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_17[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_17[playerid], 50);
PlayerTextDrawUseBox(playerid, textdraw_17[playerid], 0);
PlayerTextDrawSetProportional(playerid, textdraw_17[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_17[playerid], 0);

textdraw_18[playerid] = CreatePlayerTextDraw(playerid, 336.000000, 152.000000, "NRMG");
PlayerTextDrawFont(playerid, textdraw_18[playerid], 2);
PlayerTextDrawLetterSize(playerid, textdraw_18[playerid], 0.312500, 1.100000);
PlayerTextDrawTextSize(playerid, textdraw_18[playerid], 439.500000, 17.000000);
PlayerTextDrawSetOutline(playerid, textdraw_18[playerid], 1);
PlayerTextDrawSetShadow(playerid, textdraw_18[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_18[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_18[playerid], -2686721);
PlayerTextDrawBackgroundColor(playerid, textdraw_18[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_18[playerid], 50);
PlayerTextDrawUseBox(playerid, textdraw_18[playerid], 0);
PlayerTextDrawSetProportional(playerid, textdraw_18[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_18[playerid], 0);

textdraw_19[playerid] = CreatePlayerTextDraw(playerid, 373.000000, 154.000000, ". LT");
PlayerTextDrawFont(playerid, textdraw_19[playerid], 2);
PlayerTextDrawLetterSize(playerid, textdraw_19[playerid], 0.120833, 0.750000);
PlayerTextDrawTextSize(playerid, textdraw_19[playerid], 439.500000, 17.000000);
PlayerTextDrawSetOutline(playerid, textdraw_19[playerid], 1);
PlayerTextDrawSetShadow(playerid, textdraw_19[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_19[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_19[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_19[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_19[playerid], 50);
PlayerTextDrawUseBox(playerid, textdraw_19[playerid], 0);
PlayerTextDrawSetProportional(playerid, textdraw_19[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_19[playerid], 0);

textdraw_20[playerid] = CreatePlayerTextDraw(playerid, 387.000000, 152.000000, "Serveri");
PlayerTextDrawFont(playerid, textdraw_20[playerid], 1);
PlayerTextDrawLetterSize(playerid, textdraw_20[playerid], 0.312500, 1.100000);
PlayerTextDrawTextSize(playerid, textdraw_20[playerid], 439.500000, 17.000000);
PlayerTextDrawSetOutline(playerid, textdraw_20[playerid], 0);
PlayerTextDrawSetShadow(playerid, textdraw_20[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_20[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_20[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_20[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_20[playerid], 50);
PlayerTextDrawUseBox(playerid, textdraw_20[playerid], 0);
PlayerTextDrawSetProportional(playerid, textdraw_20[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_20[playerid], 0);

textdraw_21[playerid] = CreatePlayerTextDraw(playerid, 249.000000, 203.000000, "Noredami testi prasome prisijungti");
PlayerTextDrawFont(playerid, textdraw_21[playerid], 1);
PlayerTextDrawLetterSize(playerid, textdraw_21[playerid], 0.295832, 0.850000);
PlayerTextDrawTextSize(playerid, textdraw_21[playerid], 462.000000, 3.000000);
PlayerTextDrawSetOutline(playerid, textdraw_21[playerid], 0);
PlayerTextDrawSetShadow(playerid, textdraw_21[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_21[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_21[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_21[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_21[playerid], 50);
PlayerTextDrawUseBox(playerid, textdraw_21[playerid], 0);
PlayerTextDrawSetProportional(playerid, textdraw_21[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_21[playerid], 0);

textdraw_22[playerid] = CreatePlayerTextDraw(playerid, 230.000000, 215.000000, "su savo slaptazodziu kuri naudojote registracijos metu");
PlayerTextDrawFont(playerid, textdraw_22[playerid], 1);
PlayerTextDrawLetterSize(playerid, textdraw_22[playerid], 0.262499, 0.899999);
PlayerTextDrawTextSize(playerid, textdraw_22[playerid], 462.000000, 3.000000);
PlayerTextDrawSetOutline(playerid, textdraw_22[playerid], 0);
PlayerTextDrawSetShadow(playerid, textdraw_22[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_22[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_22[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_22[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_22[playerid], 50);
PlayerTextDrawUseBox(playerid, textdraw_22[playerid], 0);
PlayerTextDrawSetProportional(playerid, textdraw_22[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_22[playerid], 0);

textdraw_23[playerid] = CreatePlayerTextDraw(playerid, 340.000000, 250.000000, "slaptazodis");
PlayerTextDrawFont(playerid, textdraw_23[playerid], 2);
PlayerTextDrawLetterSize(playerid, textdraw_23[playerid], 0.316666, 1.149999);
PlayerTextDrawTextSize(playerid, textdraw_23[playerid], 400.000000, 96.500000);
PlayerTextDrawSetOutline(playerid, textdraw_23[playerid], 0);
PlayerTextDrawSetShadow(playerid, textdraw_23[playerid], 1);
PlayerTextDrawAlignment(playerid, textdraw_23[playerid], 2);
PlayerTextDrawColor(playerid, textdraw_23[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_23[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_23[playerid], 50);
PlayerTextDrawUseBox(playerid, textdraw_23[playerid], 1);
PlayerTextDrawSetProportional(playerid, textdraw_23[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_23[playerid], 1);

textdraw_24[playerid] = CreatePlayerTextDraw(playerid, 337.000000, 172.000000, "Vardas_Pavarde");
PlayerTextDrawFont(playerid, textdraw_24[playerid], 2);
PlayerTextDrawLetterSize(playerid, textdraw_24[playerid], 0.266667, 0.899999);
PlayerTextDrawTextSize(playerid, textdraw_24[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, textdraw_24[playerid], 0);
PlayerTextDrawSetShadow(playerid, textdraw_24[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_24[playerid], 2);
PlayerTextDrawColor(playerid, textdraw_24[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_24[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_24[playerid], 50);
PlayerTextDrawUseBox(playerid, textdraw_24[playerid], 0);
PlayerTextDrawSetProportional(playerid, textdraw_24[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_24[playerid], 0);

textdraw_25[playerid] = CreatePlayerTextDraw(playerid, 337.000000, 183.000000, "_");
PlayerTextDrawFont(playerid, textdraw_25[playerid], 0);
PlayerTextDrawLetterSize(playerid, textdraw_25[playerid], 0.600000, -0.249996);
PlayerTextDrawTextSize(playerid, textdraw_25[playerid], 303.500000, 100.500000);
PlayerTextDrawSetOutline(playerid, textdraw_25[playerid], 1);
PlayerTextDrawSetShadow(playerid, textdraw_25[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_25[playerid], 2);
PlayerTextDrawColor(playerid, textdraw_25[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_25[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_25[playerid], 2094792839);
PlayerTextDrawUseBox(playerid, textdraw_25[playerid], 1);
PlayerTextDrawSetProportional(playerid, textdraw_25[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_25[playerid], 0);


//SHOW/HIDE
TextDrawShowForPlayer(playerid, textdraw_0); //Shows Textdraw for Player.
TextDrawShowForAll(textdraw_0); //Shows Textdraw for all players.

TextDrawHideForPlayer(playerid, textdraw_0); //Hides TextDraw for player.
TextDrawHideForAll(textdraw_0); //Hides Textdraw for all players.

PlayerTextDrawShow(playerid, textdraw_0[playerid]); //Shows PlayerTextDraw for player.
PlayerTextDrawHide(playerid, textdraw_0[playerid]); //Hides PlayerTextDraw for player.

SelectTextDraw(playerid, 0xFF0000FF); //Shows cursor for player to select textdraw
